### ISSUE TITLE
Typo when checking presence of :wet_sign option

### ISSUE THREAD

**Issue by micahiriye** [jondkinney/docusign_rest#122]
Hey there! This gem is great! 

I think there is a typo when checking the "enableWetSign" option:

https://github.com/jondkinney/docusign_rest/blob/master/lib/docusign_rest/client.rb#L782

```ruby
post_hash[:enableWetSign] = options[:wet_sign] if options.has_key? :web_sign # "web_sign" instead of "wet_sign"
```

I believe this is supposed to be:

`options.has_key? :wet_sign`

**Comment by jondkinney** [comment]
@micahiriye nice catch! Would you mind submitting a PR for it?
