### ISSUE TITLE
event notification status

### ISSUE THREAD

**Issue by andrewroth** [jondkinney/docusign_rest#133]
Hi there,

I'm working on integrating docusign into a project and we would live to use callbacks.  I see some code for event notifications but there's a todo comment near it.  What is the status of this code?  Is it usable at all?  Thanks.

**Comment by tommotorefi** [comment]
@andrewroth hi Andrew, yup, event notifications work fine - you can create an envelope with event hooks and they'll get called.  

FWIW, the problem I've seen with them is they come 10-15 seconds after the actual event, so if you need to update the UI immediately after (for example) a customer signs, they can be too delayed to be of much use.

**Comment by tcopeland** [comment]
Please reopen this if you have additional questions, thanks!
