### ISSUE TITLE
docs reference private method?

### ISSUE THREAD

**Issue by arches** [jondkinney/docusign_rest#32]
I might be reading this wrong, but client.rb marks `get_account_id` as "internal" but it's referenced in the README.  I wouldn't care very much except when I set up my config and try to do what I think is the simplest example from the README, I got nothing:

```
> client.get_account_id
=> nil
> client.account_id
=> "611155" # this isn't my actual ID but it's correct in my console
```

Maybe better to replace that example with one that hits the API? `client.get_login_information` worked great as a smoke test for me, it was nice to see the wrapper return an HTTP response that contained my info.

**Comment by hoang1417** [comment]
I have same issue with @arches but it because I set this config:

```
DocusignRest.configure do |config|
  ...
  config.account_id = "***"
  ...
end
```

Removing that config make the `client.get_account_id` command run well.

**Comment by tcopeland** [comment]
@arches FWIW there was a bug in that method which has been fixed by https://github.com/jondkinney/docusign_rest/commit/d9a00d853f8173132dc84368cd8cd3f2089b8fb8.  Sounds like you and Jon thought it should be removed from the README, so if you want to open a PR I'll merge it forthwith.
