### ISSUE TITLE
Bug in Client.rb causing "The request body is missing or improperly formatted"

### ISSUE THREAD

**Issue by mesbahmilad** [jondkinney/docusign_rest#40]
The following line ( client.rb, line 411)

> tab_hash[:height]     = tab[:height] if tab[:width]

should be 

> tab_hash[:height]     = tab[:height] if tab[:height]

**Comment by tcopeland** [comment]
Fix merged to master, https://github.com/jondkinney/docusign_rest/commit/efb13a2802b5038c0c61999386f5e20d459a580a, thanks @mesbahmilad!  

I'm hoping to get a 0.2.0 release out shortly.
