### ISSUE TITLE
Version Needs Bumped

### ISSUE THREAD

**Issue by pkubat** [jondkinney/docusign_rest#66]
The last time version.rb was bumped was 2/3/2014.  There are commit with fixes since then.

For instance:
https://github.com/jondkinney/docusign_rest/commit/9661e0ddb3649a8fdce6ecb866ee55b62f53333b

Is fix is not in the gem that is published, this when one installs it has they bug in it.

**Comment by jondkinney** [comment]
I've added a note to please bundle to the master branch until a new gem release is cut. Sorry for the inconvenience! https://github.com/jondkinney/docusign_rest#usage-note

For example:

`gem 'docusign_rest', github: 'jondkinney/docusign_rest'`
