### ISSUE TITLE
INVALID_ANCHOR_TAB_STRING on example

### ISSUE THREAD

**Issue by jetienne** [jondkinney/docusign_rest#80]
Hi,

Using the very first example (enveloppe), I keep having this:
{"errorCode"=>"INVALID_ANCHOR_TAB_STRING", "message"=>"The Anchor Tab String Format is invalid. AnchorTabString \"\" is either empty or is not a single word."}

Any idea?

**Comment by jondkinney** [comment]
@jetienne I haven't done a gem release to rubygems in a very long time, but quite a bit of PRs and fixes have been merged into master since the last release. The project isn't super actively maintained right now, but if you bundle to the master branch I'm betting that that error will go away.

**Comment by tcopeland** [comment]
@jetienne thanks for the report; I've modified that first example and it should work fine now.
