### ISSUE TITLE
Regarding your note

### ISSUE THREAD

**Issue by madamkiwi** [jondkinney/docusign_rest#82]
Hello there - I saw your note and would like to help maintaining this, so let me know what I can do to help!

**Comment by jondkinney** [comment]
@madamkiwi Thanks so much for the offer, I added you as a collaborator! Let me know if there's a place you think makes sense to start. Merging in PRs? Beefing up test coverage? A new proper gem release? All of these things have been on my list for a while, but I'm definitely open to wherever you think you can add the most value or what you want to work on first. Thanks again for jumping in!
