### ISSUE TITLE
Gem Version

### ISSUE THREAD

**Issue by ebinujohn** [jondkinney/docusign_rest#87]
The gem version is still 0.1.1. Does it need to be updated so that new Gem version flows in on bundle update?

**Comment by jondkinney** [comment]
@ebinujohn I'd suggest bundling to the git master branch for now like the Readme indicates: https://github.com/jondkinney/docusign_rest#usage-note

**Comment by ebinujohn** [comment]
@jondkinney Thank you! I dont know how I missed that section. :(
